[package]
name = "broadphase_experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed = { version = "1.27.0", features = ["num-traits"] }
nalgebra = "0.33.0"
rand = "0.8.4"
lindel = "0.1.1"
rayon = "1.10.0"
hilbert = "0.1.2"
arrayvec = "0.7.4"

